export const SET_LOADING_LIST_PRODUCT = 'SET_LOADING_LIST_PRODUCT';
export const GET_SHORT_LIST_PRODUCT = 'GET_SHORT_LIST_PRODUCT';
export const SET_SHORT_LIST_PRODUCT = 'SET_SHORT_LIST_PRODUCT';

// __________ITEM_PRODUCT_____________
export const SET_LOADING_ITEM_PRODUCT = 'SET_LOADING_ITEM_PRODUCT';
export const GET_ITEM_PRODUCT = 'GET_ITEM_PRODUCT';
export const SET_ITEM_PRODUCT = 'SET_ITEM_PRODUCT';

export const CHANGE_ITEM_PRODUCT_NAME = 'CHANGE_ITEM_PRODUCT_NAME';
export const CHANGE_ITEM_PRODUCT_LINK = 'CHANGE_ITEM_PRODUCT_LINK';
export const CHANGE_ITEM_PRODUCT_COST = 'CHANGE_ITEM_PRODUCT_COST';
export const CHANGE_ITEM_PRODUCT_DETAILS = 'CHANGE_ITEM_PRODUCT_DETAILS';
export const CHANGE_ITEM_PRODUCT_IMAGE_NAME = 'CHANGE_ITEM_PRODUCT_IMAGE_NAME';