export const GET_SHORT_LIST_PRODUCT = 'GET_SHORT_LIST_PRODUCT';
export const SET_SHORT_LIST_PRODUCT = 'SET_SHORT_LIST_PRODUCT';
export const SET_LOADING = 'SET_LOADING';

export const GET_ITEM_PRODUCT = 'GET_SHORT_LIST_PRODUCT';
export const SET_ITEM_PRODUCT = 'SET_SHORT_LIST_PRODUCT';