// __________LIST PRODUCTS_____________
export const SET_LOADING_STORE = 'SET_LOADING_STORE';

export const GET_SHORT_LIST_PRODUCT = 'GET_SHORT_LIST_PRODUCT';
export const SET_SHORT_LIST_PRODUCT = 'SET_SHORT_LIST_PRODUCT';

export const SELECT_PRODUCT_PARAMETER = 'SELECT_PRODUCT_PARAMETER';

export const GET_OBSERVABLE_PRODUCT = 'GET_OBSERVABLE_PRODUCT';
export const SET_OBSERVABLE_PRODUCT = 'SET_OBSERVABLE_PRODUCT';
export const UNSET_OBSERVABLE_PRODUCT = 'UNSET_OBSERVABLE_PRODUCT';

// __________PRODUCT_____________
export const SET_LOADING_PRODUCT = 'SET_LOADING_PRODUCT';
export const SET_PRODUCT_LINK_MATCH = 'SET_PRODUCT_LINK_MATCH';

export const SET_PRODUCT = 'SET_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const POST_PRODUCT = 'POST_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

// __________RESPNSE BAR_____________
export const SET_RESPONSE_STATE = 'SET_RESPONSE_STATE';
export const CLEAR_RESPONSE_STATE = 'CLEAR_RESPONSE_STATE';

export const SET_REDIRECT = 'SET_REDIRECT';
export const REDIRECT_IS_PASSED = 'REDIRECT_IS_PASSED';

// __________USER NAV BAR_____________
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const LOGIN_CURRENT_USER = 'LOGIN_CURRENT_USER';
export const SIGN_OUT_CURRENT_USER = 'SIGN_OUT_CURRENT_USER';

// __________CART_____________
export const SET_CART = 'SET_CART';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';

export const SET_PRODUCT_QUANTITY_IN_CART = 'SET_PRODUCT_QUANTITY_IN_CART';

